name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to Snake! Thank you for filing your first issue, we will look right into it!'
        pr-message: 'Welcome to Snake! Thank you for cooperating with us, we will check your proposed changes soon!'
